### ISSUE TITLE
Error in install: Path outside the workspace

### ISSUE THREAD

**Issue by Schmavery** [def-lkb/merlin-extend#11]
Seems like there could possibly have been an issue introduced by https://github.com/let-def/merlin-extend/commit/4d6c12da2f0f7cdc98e86f6a23f0be8e9f09ec00

I was trying to `opam install reason` just now (version 5.4.0), and it failed when installing the merlin-extend dep.

```
$ opam install reason
The following actions will be performed:
  ∗ install merlin-extend 0.4   [required by reason]
  ∗ install reason        3.5.0
===== ∗ 2 =====
Do you want to continue? [Y/n] Y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[merlin-extend.0.4] found in cache
[reason.3.5.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of merlin-extend failed at "/Users/avery/.opam/opam-init/hooks/sandbox.sh build dune build -p merlin-extend -j 7".

#=== ERROR while compiling merlin-extend.0.4 ==================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#b237de41
# path        ~/.opam/portable_daemon/.opam-switch/build/merlin-extend.0.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p merlin-extend -j 7
# exit-code   1
# env-file    ~/.opam/log/merlin-extend-7012-d2d111.env
# output-file ~/.opam/log/merlin-extend-7012-d2d111.out
### output ###
# Path outside the workspace: ../merlin_extend/META from .
```

It seems like the the path in the error (`../merlin_extend/META`) was added in the change I linked above. Manually installing `opam install merlin-extend.0.3` does work, so it seems like the issue was introduced since then, at least.

Disclaimer: I'm not a very experienced dune-er so sorry if this is a user error!

Current workaround:
```
opam install merlin-extend.0.3
opam install reason.3.4.0
```

**Comment by let-def** [comment]
Yes it was done intentionally to prevent breaks from the migration to dune. Now it breaks in another component... Wonderful.
Reason should already be using the correct paths, I will push a second update that remove the hack for the transition.

**Comment by Schmavery** [comment]
Thanks for looking at this so quickly! :)

**Comment by Schmavery** [comment]
Thanks again, just tried `opam install reason` again after an `opam update` and it worked no problem :)
