### ISSUE TITLE
Compile failure using OCaml 4.03

### ISSUE THREAD

**Issue by jberdine** [def-lkb/merlin-extend#2]
Maybe this is not supposed to work, or is just me?  Short error is:

```
# File "extend_helper.ml", line 24, characters 37-58:
# Error: The constructor Asttypes.Const_string belongs to the variant type
#          Asttypes.constant
#        but a constructor was expected belonging to the variant type
#          Parsetree.constant
```

[Transcript](https://gist.github.com/jberdine/a9c659b49b3afe03bd228191d5e8409a)

**Comment by objmagic** [comment]
@jberdine fix in PR #3 

reason is some AST constants are moved from Asttypes to Parsetree during 4.03.0

you can try `opam pin add merlin_extend https://github.com/objmagic/merlin-extend.git#fix-ast-constant-4030` if in hurry
