### ISSUE TITLE
optcomp/cppo syntax support

### ISSUE THREAD

**Issue by db4** [def-lkb/merlin-extend#7]
There is a long-awaited [optcomp/cppo syntax support](https://github.com/ocaml/merlin/issues/202) feature in merlin. Is merlin-extend a way to implement it? Do you think it's hard enough? (this project lacks docs so I wold like to know your opinion before looking deeper)

**Comment by let-def** [comment]
Sorry for the looong delay :).
I don't think merlin-extend is the best way to get this feature. Merlin has limited support for `-pp` flag which passes the source through a preprocessor. That's a good starting point! (and has already been used for cpp-like processing).
